### ISSUE TITLE
herokuapp website doesn't work

### ISSUE THREAD

**Issue by ITAYC0HEN** [potherca-blog/github-find-typos#2]
Currently, the project's website link has an error - https://github-find-typos.herokuapp.com/

![image](https://user-images.githubusercontent.com/20182642/46334407-95452f00-c62c-11e8-91bb-a115d0d57d51.png)

Could be related to #1 

Also, I wasn't able to serve this website locally using the V-0.4 release by executing 
```
$ composer update
$  php -S localhost:8888
```

**Comment by Potherca** [comment]
I've managed to get things working locally but I've not yet had luck getting the _exact_ same code to work on Heroku. It could be related to PHP versions but I'd have to investigate further.
